Update BLT and change BLT TPL configuration to use new macro
LLNL/camp pull request #138
Opened 2023-09-07 17:43 UTC by johnbowen42

BLT has a new macro `blt_install_tpl_setups` that will install files such as `BLTSetupOpenMP.cmake` etc to enable configuration of TPL targets at the build time.  For example, if camp uses CUDA, a repo linking to camp can re-evaluate the compile and link flags inside `BLTSetupCUDA.cmake` at compile at configuration time, correcting possible errors caused by incorrect link flags, etc.  

This PR moves the BLT commit to include this macro, and updates camp's cmake to use the new macro,

2023-09-12 17:47 UTC, davidbeckingsale requested changes

2023-09-12 17:47 UTC, davidbeckingsale commented on cmake/campConfig.cmake.in
> +include("${CMAKE_CURRENT_LIST_DIR}/BLTSetupTargets.cmake")
This should come before campTargets, and you should remove the old code.

2023-10-04 16:59 UTC, davidbeckingsale approved these changes

2023-10-05 09:11 UTC, trws commented
@homerdin it looks like something unfortunate is happening with the way we're getting sycl here, do you know if anything has changed in their container/apt setup lately?

2023-10-23 18:02 UTC, johnbowen42 commented
@homerdin I reran the pipeline and it looks like its still falining.  Do I need to rebase to include the fix?

2023-10-23 20:03 UTC, merged