add get_event_erased to resource class
LLNL/camp pull request #66
Opened 2021-06-16 23:13 UTC by artv3

Since we pass back a erased resource type in https://github.com/LLNL/RAJA/pull/1029, we need to add get_event_erased method class to the resource class.

2021-07-06 18:47 UTC, trws requested changes
With the suggested change, or an equivalent one, I'm good with this.

2021-07-06 18:47 UTC, trws commented on include/camp/resource.hpp
> +      Event get_event_erased() { return m_value->get_event(); }
```suggestion
      Event get_event_erased() { return m_value->get_event_erased(); }
```

2021-07-06 19:01 UTC, trws commented
@artv3: Error from Travis, looks like the ContextInterface doesn't have the method to pass it through:

```
1: /home/raja/include/camp/resource.hpp:94:50: error: 'class camp::resources::v1::Resource::ContextInterface' has no member named 'get_event_erased'
```

2021-07-21 18:48 UTC, artv3 commented
Thanks @trws, could we sync up after the release to try to fix this? I'm off the next few days but hopefully after we can sort it out. 
This PR is needed for the following RAJA branch - https://github.com/LLNL/RAJA/pull/1029.

2021-07-21 19:08 UTC, trws commented
Sure.  The problem should be solved by adding a `get_event_erased` right next to the `get_event` proxy method [here](https://github.com/LLNL/camp/pull/66/files#diff-a31e2568f20cbb0cdffc68f85d78c21e6df4a6ac05561a1a0205befd4336554cL106).

2021-07-21 20:13 UTC, artv3 commented
Hooray! all test pass!

2021-07-21 22:11 UTC, trws approved these changes
Looks great, thanks!

2021-07-21 22:12 UTC, merged