first cut requiring c++17
LLNL/camp pull request #95
Opened 2021-12-09 17:45 UTC by trws

Only used a bit of basic c++17 to pull some of the crud out of tuple.
Now uses overload resolution for get rather than template instantiation.

2021-12-09 20:44 UTC, rhornung67 commented on CMakeLists.txt
> +      message(FATAL_ERROR "CAMP and the RAJA framework no longer support c++ standards below c++17, select a c++ standard of 14 or higher")
This message is contradictory and should be reworded.
```suggestion
      message(FATAL_ERROR "CAMP and the RAJA framework no longer support c++ standards below c++17, select a c++ standard of 17 or higher")
```

2021-12-09 20:45 UTC, rhornung67 requested changes
fix issue with c++ standard message for CMake.

2021-12-10 15:38 UTC, rhornung67 approved these changes

2025-11-12 22:51 UTC, kab163 commented
Can This be closed? - Just saw this PR, probably could have been helpful when I attempted this update a few months back.. whoopsies!

2026-05-05 16:12 UTC, closed without merging

2026-05-05 16:12 UTC, kab163 commented
We are about to add C++20 - closing this in favor of the other PR